---
## REF: https://github.com/billimek/k8s-gitops/blob/2d48e3ba92d984e21e5c2267d10d48e867898e0b/default/blocky/blocky.yaml
## REF: https://github.com/jr0dd/home-ops/blob/main/cluster/apps/networking/blocky/helm-release.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app blocky
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 1h
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      blocky:
        replicas: 2
        strategy: RollingUpdate
        pod:
          hostUsers: false
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            seccompProfile: { type: RuntimeDefault }
        containers:
          app:
            image:
              repository: ghcr.io/0xerr0r/blocky
              tag: v0.29.0@sha256:a6d99f323d3036a99a3767a52ad612f4d8f3f31167492bfc14d4ea57b24cdfd0
            env:
              TZ: America/Chicago
            # resources:
            #   requests:
            #     cpu: 10m
            #     memory: 50Mi
            #   limits:
            #     memory: 750Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                add: ["NET_BIND_SERVICE"]
                drop: ["ALL"]
      cache:
        containers:
          server:
            image:
              repository: public.ecr.aws/docker/library/redis
              tag: 8.6.1@sha256:315270d166080f537bbdf1b489b603aaaa213cb55a544acfa51feb7481abb1c0
            command: redis-server
            env:
              REDIS_REPLICATION_MODE: master
            resources:
              requests:
                cpu: 10m
                memory: 10Mi
              limits:
                memory: 100Mi
      frontend:
        strategy: RollingUpdate
        pod:
          hostUsers: false
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            seccompProfile: { type: RuntimeDefault }
        containers:
          main:
            image:
              repository: ghcr.io/gabeduartem/blocky-ui
              tag: 1.6.1@sha256:35e67a68a6ef15ad43d3b9913ab7e667deaddcb022e414eacc8070a1450b4441
            env:
              BLOCKY_API_URL: "http://{{ .Release.Name }}-app:4000"
            probes:
              liveness:
                enabled: true
                type: HTTP
              readiness:
                enabled: true
                type: HTTP
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      nodeSelector:
        kubernetes.io/arch: amd64
    service:
      app:
        controller: *app
        ports:
          http:
            port: &port 4000
      dns:
        controller: *app
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          metallb.io/loadBalancerIPs: ${BLOCKY_IP_ADDRESS}
        ports:
          http:
            port: *port
            protocol: TCP
          tcp:
            port: 53
            protocol: TCP
          udp:
            port: 53
            protocol: UDP
      cache:
        controller: cache
        ports:
          http:
            port: 6379
      frontend:
        controller: frontend
        ports:
          http:
            port: &fe-port 3000
    route:
      internal:
        enabled: true
        kind: HTTPRoute
        parentRefs:
          - name: envoy-internal
            namespace: networking
            sectionName: https
        hostnames:
          - "{{ .Release.Name }}.${INTERNAL_HOSTNAME}"
        rules:
          - backendRefs:
            - name: blocky-frontend
              port: *fe-port
    serviceMonitor:
      main:
        enabled: true
        serviceName: blocky-app
        # selector:
        #   matchLabels:
        #     app.kubernetes.io/name: *app
        # labels:
        #   release: kube-prometheus-stack #idk why this is required
        endpoints:
          - interval: 30s
            path: /metrics
            port: http
            scrapeTimeout: 10s
    persistence:
      config:
        enabled: true
        type: configMap
        name: blocky
        advancedMounts:
          blocky:
            app:
              - path: /app/config.yml
                subPath: config.yaml
