apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: calibre
spec:
    secretTemplates:
        - name: restic-calibre
          stringData:
            RESTIC_REPOSITORY: ENC[AES256_GCM,data:A/SDutzzIxqwFYlFU3fAgbAnSI9AZrcjCa6XmjRvFal9W5OgZ98Vu5qGkyLmpuU/vc/WLqp1PQ==,iv:+66J9Knm5Zk//pDOiiPEpatdtxDS7IndIZpDH3QqQ6c=,tag:BYksagoYDs8vZvjixdkWdw==,type:str]
            RESTIC_PASSWORD: ENC[AES256_GCM,data:WlCO/smb/gRO9HSHa7sDa2ZdM1E=,iv:FQKtJAkQxenAtmFn9cexUqEvaDdMSt1TFZVxIzIeT9U=,tag:ekdvYIwsn7DszeS5AGHY8Q==,type:str]
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:XbMC1BziCbVVg8GtYI5dOE9FbWc=,iv:S5MPvFUXCD0fLz7x/U1ZM9Bi5EAlS2frOsA/JlioySg=,tag:gx+fL6MuutmF9AGo3vLiqQ==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:SFTB8z1Nh3Z7SSXaauK/tN5gt1iNwwVfXh0FWxUNgydr5jy8,iv:FdQlDYO15QQLP9UizmJGR0pHfzdsGAqbs8XrQ0j5aqQ=,tag:e8a3Jz8/3GSjXB/zSf5bhQ==,type:str]
        - name: calibre
          stringData:
            HARDCOVER_TOKEN: ENC[AES256_GCM,data:ExNOXb5KtOxCEF2pWtAwCUIRLn7Ly00LPSYatVXZqxQ23BV21xnVU9xAA+EIJ2OcXYkn4EA//jkYXSP3jAEGKUhi533cCldRhXJW7xPcHANUHaRH+MDMMufeNi2OgPcKHFeOis2JOLb8zKQeHkmpiJRdw8hFvaBTS4qZVa+PaxyktClMELKyjVDjHq8Jvg/HXMZVuaBOeHmxGY5zMNsoGwlhZCyWJMsC+lPMElTVGOsPLIWnG2FdNF1aOSVfQwxUdhrve8Jn+6zYcfyM0rkDGFIEpBiqpKxNNgMHrGVnC4sgKOpqBnjaO4oN+PJ7y1UJric3yZiaZDeac5n5KuOaG1Xp9pT+SxK/WvHci+NNV9AdnY4GTVOFI3xzbtOMG3WbRLYF18kIK3mKV+/UDF8titWW3sYzXpxRY3rCOsw4WQ2OB4zeTLRs3QpJVlSgjl+TlVFHU1bfKuPj8gAI8kMOGir49UZP4obits8hDUCWs8mOofi3pblou8oGfstdQTL8h8nGdjf3rHGZNx12ibjBMppW9O4Uvo4HyclbCishz8gjrO/kDm73mOO/xwNlkU1vHaPft67dFR8NjQm8nWauqwo/wTZPr35FAFZ4hnD0w0qJcYTYSUfACN7lZqWsClHkL/9yBiUMGyUM15fF8E/pxUZ3mLJk2rs2de5/m6LQdonWbFhLFILnKnGckLW541SVdJ5ptuEUpQ0svnZt,iv:iuHfjlxgJbgE/SWxO+hmmQnyYVw1ZBJ9fCZ/WV6oTdA=,tag:ZBD+Hq3HX8oBf9vx8KXhNw==,type:str]
            HARDCOVER_TOKEN_EXPIRES: ENC[AES256_GCM,data:4nXJMbPf/bD0Tg==,iv:425iIknZcvrvXNUQr5IaVuRmi1l48sbfsCRXDwncADg=,tag:weUqJ9oQObXsp4D4OjsOTQ==,type:str]
sops:
    age:
        - recipient: age1a7ud8ygel5wxlem8p9ukahjmnsg42qk6z94033hav62ke2u74pvqgf9vts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dmhBT0hWRVpzSEhkUkVw
            TDNtVjQxWER0UHVnWVhxeFAvWDZYOWJuWWowCmRyMEUrVXBBdGVUSlRHRklYcWF1
            aVlIQ1BVSXdLd1IzRjU3Q3BFa05MRXcKLS0tIGZDMFVyUC9qekNPMGFPOXRaa3cz
            K0paRTMrdVlMUlJrUXlPL2VqOXdIaTAKpk/RGLVISSZKtjiZoKd7GvjobZwr+xr5
            +gwngTyFfrTjfMbiJPvy+wVefK0aJ2BWMQ2H8YO3gmd7kdsqlm29uQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T20:52:05Z"
    mac: ENC[AES256_GCM,data:M0DrTt4y+P/nsSJWU5REDw6MvcJ9JRFHX8NzN5pcOWk/rNoJoLbHZ2TyWd2fDycLx3im50p9UIatPOw8OiwZJ28LVHYrDAYHsomzg+rE3nixgOCF5Y7cXzhsjQdCITSFCpirbnFlfiYAjP/D7MqfBwejGkD2/dnvP3i4wMJ269w=,iv:Sp2m19fB6l++qx2rnqCfBcWRBGkM/DPn0axOfkgr2cA=,tag:UzQezkn9fqC10GvNBbhGsA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
