apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: seerr
spec:
    secretTemplates:
        - name: restic-seerr
          stringData:
            RESTIC_REPOSITORY: ENC[AES256_GCM,data:xElvxPvXyatf36uVLw9oxKgzGaKF6V4RONKUrFSzfAgSCuOmK/EgzI9y/iEvJUV93utTN/4=,iv:yzvl6Qv/1cGtsCY+fyrUw047NSkyZLLiyHmAvbofGKQ=,tag:o+KsqFXN01AsgA50dSRMsg==,type:str]
            RESTIC_PASSWORD: ENC[AES256_GCM,data:29beomudR1f5Kjb8FMZPp+QSSzY=,iv:AERc0vqNb/cNElEZZTP7LYrVZxmlTXAI+kVOHG+Aq1Y=,tag:TLWhJIftoT0uXiLVROO8Dg==,type:str]
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:WQzDWPeJYmHWfpKfNVA0JltlF2M=,iv:dC2c0iM+tkaKfZxUmD3LLSnu6a8fu0nsxBiBEUV+txY=,tag:fR6wLazK8Fy7W8+6h11FIg==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:OenuoCdvMXLWqND2TbImXIN7lkdvq2u7mtIr3FeEgh7t526g,iv:ombnaia2qmELCFzOkg67cjKuuYrvXgvzSlzDc7JSUu4=,tag:CNXPtgChL2dV5u0jzw0BlQ==,type:str]
sops:
    age:
        - recipient: age1a7ud8ygel5wxlem8p9ukahjmnsg42qk6z94033hav62ke2u74pvqgf9vts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyVTF1aUpobnNSK3NCWEdJ
            NTZqdTdwT204dDJSRU9jcXBFeXQ1OXl4cW1ZCnlOUy9KSExqYXhPLzdyd3FySW1u
            d3lCcTloT2tRRzhZVkFQNlVrdWF6a00KLS0tIEVmK3BpMVVHK2dTemc5UGFpYWJh
            N3g2MncwaFJPM3dmVThBYWNYcGNzUG8KR+EaqxZslu9GQIm+LJWI8Vo9xhua1EUz
            GaiIAbXj5MZ4INzk032LV1P4+Py6MhuNLpy6njzHDecBIFCttyH55g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T22:09:04Z"
    mac: ENC[AES256_GCM,data:cH27Nj9+BFTIavIi3VEDh2t2upQAgaUw07T8QXQgnwNBSGvp34CkgnrW/HvEEWt5UHWIDfGI2wO+9Iq+GiW579KmsMFlL4Z7FAAS/UCo0UEBtozqB4s58O0oERKsqJyLcTnYKHNU/eaqarAw68jUbGkghZCE2GiTjbDg121ka5U=,iv:+4Vm5AcdO2pNuABnloBInwEBNGRJhh/Tl2G+ReIi1xw=,tag:s5jthtQXL0KmMa7h/j6aNA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
