---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  chartRef:
    kind: OCIRepository
    name: cert-manager
  interval: 1h
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: quay.io/jetstack/cert-manager-controller
      tag: v1.20.3@sha256:6c13d61e0348a5bc3477f8ea9a928624300b30d19b1c72a7d2b90372fc713db4
    installCRDs: true
    webhook:
      image:
        repository: quay.io/jetstack/cert-manager-webhook
        tag: v1.20.3@sha256:a61e817632cebed3bb59a189327e786fa3fdd7597167d994a1848d98fd55848f
    cainjector:
      image:
        repository: quay.io/jetstack/cert-manager-cainjector
        tag: v1.20.3@sha256:06ad347fe0dc2eb84cc355c26f6752e05e87dceb6447f5cd29b963dd66dfd8bd
    extraArgs:
      - --enable-gateway-api
    dns01RecursiveNameservers: 1.1.1.1:53,9.9.9.9:53
    dns01RecursiveNameserversOnly: true
    podDnsPolicy: None
    podDnsConfig:
      nameservers:
        - "1.1.1.1"
        - "9.9.9.9"
    prometheus:
      enabled: false
