---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  chartRef:
    kind: OCIRepository
    name: cert-manager
  interval: 1h
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: quay.io/jetstack/cert-manager-controller
      tag: v1.21.2@sha256:70f532fd9cfde0b09d55687200942399d89838bc2d5d5b45152eb799a15912b8
    installCRDs: true
    webhook:
      image:
        repository: quay.io/jetstack/cert-manager-webhook
        tag: v1.21.2@sha256:a60e2dac46dbb8a7f3df95c54ce941012f54c2fe022f0ee55aaa1ab40ed957ae
    cainjector:
      image:
        repository: quay.io/jetstack/cert-manager-cainjector
        tag: v1.21.2@sha256:c85268c64f2e0e76684bf5fe8906caff34b82523561c6affe0fae3546bd87562
    extraArgs:
      - --enable-gateway-api
    dns01RecursiveNameservers: 1.1.1.1:53,9.9.9.9:53
    dns01RecursiveNameserversOnly: true
    podDnsPolicy: None
    podDnsConfig:
      nameservers:
        - "1.1.1.1"
        - "9.9.9.9"
    prometheus:
      enabled: false
