---
apiVersion: operator.kairos.io/v1alpha1
kind: NodeOpUpgrade
metadata:
  name: hadron-v0-4-0-kairos-v4-1-2-k3s-v1-36-1
spec:
  image: quay.io/kairos/hadron:v0.4.0-standard-amd64-generic-v4.1.2-k3s-v1.36.1-k3s1
  nodeSelector:
    matchLabels:
      kairos.io/managed: "true"
  concurrency: 1
  stopOnFailure: true
  uncordonOnFailure: true
  upgradeActive: true
  upgradeRecovery: false
