---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
spec:
  chartRef:
    kind: OCIRepository
    name: envoy-gateway
  interval: 1h
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    # global:
    #   imageRegistry: mirror.gcr.io
    config:
      envoyGateway:
        provider:
          type: Kubernetes
          kubernetes:
            deploy:
              type: GatewayNamespace
    deployment:
      envoyGateway:
        image:
          repository: docker.io/envoyproxy/gateway
          tag: v1.8.2@sha256:6b86fcef4f012fff1edc452db891ae6d09757e385305c73f5022c32550258d26
