---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
spec:
  chart:
    spec:
      chart: metallb
      version: 0.16.0
      sourceRef:
        kind: HelmRepository
        name: metallb
  interval: 1h
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      image:
        repository: quay.io/metallb/controller
        tag: v0.16.0@sha256:615b454c45e424e61d1f82c916ad7ab8c11ef2ba09d3ec4b0b64458e4058ff2b
    speaker:
      image:
        repository: quay.io/metallb/speaker
        tag: v0.16.0@sha256:70e7f83255af2e96acfd574ac9f049745639deb2746d35e988008afcc0b80dbd
      livenessProbe:
        enabled: true
        failureThreshold: 3
        initialDelaySeconds: 15
        periodSeconds: 30
        successThreshold: 1
        timeoutSeconds: 10
      frr:
        image:
          repository: quay.io/frrouting/frr
          tag: 10.6.1@sha256:813497af103e972600f6161012b3bf2a2a1c5ea10d09cd1eacd74f1dc510a57b
