apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: shelfmark
spec:
    secretTemplates:
        - name: restic-shelfmark
          stringData:
            RESTIC_REPOSITORY: ENC[AES256_GCM,data:VRvRgxIwltigUTZueudc2P5kBcZA/N/pHPe0FyUi8SCOE7EG72Pld/hgLM654SZEI/rEsHYtj2vn,iv:QN5HwxCwI9JJBVh7qpDwANGRgBXH3cHPhihQuY6pnOQ=,tag:r85MFgTkPCTAqzK9VAB8hg==,type:str]
            RESTIC_PASSWORD: ENC[AES256_GCM,data:JUIUYsYXpabJeiJOckhpblIdIgs=,iv:+5rAwAPvNZjhAHZ6VS9lqzi1SUEHgeT1h3/sZTLUqvA=,tag:XMfl10yOwwvRp/IpoEtWBA==,type:str]
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:nWy39pPPP8jVHBkYcb2jcTv/MeU=,iv:+z5sXLS19u2ZndqNJNx8ASmgKczaZFD6CnTt6gjp+So=,tag:uebgsoksAARpl0LIBQNIxg==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:uOsOPdyO/aeQ4u3xtlumxCM6XILT9c0cv6tr1R7FIAmCJFJ9,iv:JhqaVV5kvX+qlCEect+FrCaxOXL+MrGvkJO4snqVyLI=,tag:DdzviU7vsSM8+SqddU9eIw==,type:str]
        - name: shelfmark
          stringData:
            PROWLARR_API_KEY: ENC[AES256_GCM,data:kg/+HHjD9/t0MO7/GqJM4iuZ3iXuBf8A+fnN8jQteUQ=,iv:eD0FCinZbJgnivBUTt9TLRigXf9AE9eBMeeRrayxE2Q=,tag:lAutTRoBzuTZRGp0UVe05w==,type:str]
            HARDCOVER_API_KEY: ENC[AES256_GCM,data:nzfhILF50nxPsBurdo2m9LVPjeDAEQuIcmANsAmLKEDdPRmjXmR7dS+ruuUPQirxSRVG2DgO3DBtdSrubA7lxVX0AjX9AlwqlDBNivm3vAkVAMmY/lQC2gEWmQZ7ouZVxHHaYp1+5NzsisIqN+1jXKM9pr/DlfsI8b4X3erhbThbX6AOZ1jj+a9Ym0PfHNMRBhORhDuhh0eHkusJnPcrsOvmmCJEV64bBSwCX8+J3rHfX0Tw1WI037fO3qcvwxLirX+bEP8bTiU7mLAwdIxAeKFDNeIPNqxeHlQhlVAbyBTKDQjfdZ5wDUL8zpcPz2mj8eaNz06GR2m6uoCt5KTnx8Ickq9v9vN0EHHmIF0vQjNJneGZ2LNlLDE4iHy3AMs8HTitGs1mlVPUHScuKxJr9qBuvbKI2gEZTsjlkijF8JyZCdEtrlKWk65+ni5yPXqyvalgNUzapGZBSxVIehXwStUOMhy0K62uCh5jMgr8ivyDRr/okPmHXlxtFcWiEpPp412MaB03N4JBjpi95L9vAE8rAb4Fj8b4QZcZQ+mStJSX/qS2oBLYIzT3UixonMWln3nbxruhViq1lA7ae92YRMrPJAXj8EYe1FWHyzhK5Lw0JYC+v+YMdE1KN2e+5d+2lW8l/PKBSYRDAHNI3vpycsHByudAWST93NMQFqO1yykIo3Rtiod3WXJ7g2HatTXVVFTQf7mheEIkxUkZ,iv:mwp1F21NOd8V+pAeKbWfTIlEfycWaHpkKRW9GBGkDdg=,tag:rnBJxoB91/4TsiPkRjQ6Tw==,type:str]
            HARDCOVER_API_KEY_EXPIRES: ENC[AES256_GCM,data:Pz9H3RUDbUo/gQ==,iv:z5PV0s9QGpnKjmjE1QIQdvqEFQi9VYNhr5Pjhfpf2nY=,tag:BYsraaDkSTQRQvt8vPlU1w==,type:str]
sops:
    age:
        - recipient: age1a7ud8ygel5wxlem8p9ukahjmnsg42qk6z94033hav62ke2u74pvqgf9vts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRb1FRT3pMQi9ab0dsMXUr
            Vm5EckpnVS80b0dSQzVRMTZuUkVoRUNGdG5BCjdHNnZJVnN4Ly92bHNpTHl3OEM5
            QXdYSERhYVFXU1V1WkhydDNVaTk3WUUKLS0tIENSMjZjTWsyU2xDVlZ5T2g5ZDJB
            U29ZUk9LSEIzL1NNMHBqQzJNd0V0VzAKOVUe3B4PoAZWog2423eFifygFcKOJJoI
            hv/a7NGzhxiigg0LmGVQwcIsB1j17JPRFMSN5TEFMvBXXUP5fULpSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T20:29:18Z"
    mac: ENC[AES256_GCM,data:9d8VuQCO6DkuGfpKmITt2DHII/7bJEztwW0bfZgMXN7A6WumGlN0TPe/e276SDdctxZBd2IphAeDSeUJh/HF/jBtwzU+Kx66z/WqJsz4Llse/pvsYhpfV63uGooL+6riaVlQPp0awV/cqOIFQ6XOaVuaqftTgEIzTDOmacPJRlk=,iv:cUzpW2v4kWhati+epa1uoCwHssEDb04AC0nHHZsUSQ4=,tag:zpJMb2owdWdKJ5vQqBPaNw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
