name: "Kairos Update"

on:
  workflow_dispatch:
  schedule:
   - cron: "22 9 * * 0"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/kairos-update.yaml"

jobs:
  karios-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      
      - name: Generate Token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: generate-token
        with:
          app-id: ${{ secrets.CPR_APP_ID }}
          private-key: ${{ secrets.CPR_APP_PRIVATE_KEY }}

      - name: Install Nix
        uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable

      - id: update
        run: nix develop .#ci --command task kubernetes:ci-kairos-update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: Update kairos version
          title: 'Update kairos version'
          draft: false
          branch: chore/update-kairos
          delete-branch: true
          body: |
            Update kairos version
            - [openSUSE][os]
            - [Kairos][kairos]
            - [k3s][k3s]
            
            
            Auto-generated by [create-pull-request][cpr]

            [cpr]: https://github.com/peter-evans/create-pull-request
            [os]: ${{ steps.update.outputs.opensuse_url }}
            [kairos]: ${{ steps.update.outputs.kairos_url }}
            [k3s]: ${{ steps.update.outputs.k3s_url }}
